import dayjs from 'dayjs';

export function toCsv(rows, columns) {
  const header = columns.map((c) => `"${(c.title || c.dataIndex || '').replace(/"/g, '""')}"`).join(',');
  const body = rows
    .map((row) =>
      columns
        .map((c) => {
          const v = typeof c.render === 'function' ? c.render(row[c.dataIndex], row) : row[c.dataIndex];
          const s = v == null ? '' : String(typeof v === 'object' ? JSON.stringify(v) : v);
          return `"${s.replace(/"/g, '""').replace(/\n/g, ' ')}"`;
        })
        .join(',')
    )
    .join('\n');
  return `${header}\n${body}`;
}

export function downloadCsv(filename, rows, columns) {
  const csv = toCsv(rows, columns);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${dayjs().format('YYYYMMDD_HHmm')}.csv`;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}

export function printReport({ title, schoolName = 'School Report', period = '', html }) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);
  const doc = iframe.contentDocument || iframe.contentWindow.document;
  doc.open();
  doc.write(`<!doctype html><html><head><title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 28px; color: #1f2937; }
  h1 { font-size: 20pt; margin: 0 0 4px; }
  h2 { font-size: 14pt; margin: 24px 0 8px; color: #1f2937; }
  .meta { color: #6b7280; font-size: 10pt; margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; margin: 6px 0 18px; font-size: 10pt; }
  th, td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; text-align: left; }
  th { background: #f3f4f6; font-weight: 600; }
  .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 16px; }
  .kpi { padding: 10px; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; }
  .kpi-label { font-size: 9pt; color: #6b7280; }
  .kpi-value { font-size: 16pt; font-weight: 700; }
  .footer { margin-top: 30px; font-size: 9pt; color: #9ca3af; text-align: right; }
  @media print { body { margin: 0.4in; } }
</style></head><body>
<h1>${title}</h1>
<div class="meta">${schoolName} · ${period} · Generated ${dayjs().format('DD MMM YYYY, HH:mm')}</div>
${html}
<div class="footer">Generated by Classbridge Analytics</div>
</body></html>`);
  doc.close();
  iframe.contentWindow.focus();
  iframe.contentWindow.print();
  setTimeout(() => document.body.removeChild(iframe), 1000);
}
