import React, { useEffect, useRef, useState } from 'react';
import { App as AntApp } from 'antd';
import { Printer, Download, RefreshCw, FileText, FileType, AlertTriangle } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from '@/components/ui/dialog';
import {
  Tooltip, TooltipContent, TooltipProvider, TooltipTrigger,
} from '@/components/ui/tooltip';
import { Skeleton } from '@/components/ui/skeleton';

import { hrService } from '../services/hrService';

const DOC_TITLES = {
  payslip: 'Payslip',
  appointment_letter: 'Appointment Letter',
  experience_letter: 'Experience Letter',
  relieving_letter: 'Relieving Letter',
  form_16_part_b: 'Form 16 — Part B',
};

/**
 * HrDocumentViewer
 *  - Default: calls hrService.generateDocument(docType, employeeId, payslipId)
 *  - Override: pass `loadFn` that returns { html_content, meta } — used for
 *    Form 16 etc. where the document is generated by a different RPC.
 */
export default function HrDocumentViewer({ open, onClose, docType, employeeId, payslipId, employeeName, title, loadFn }) {
  const [loading, setLoading] = useState(false);
  const [html, setHtml] = useState('');
  const [error, setError] = useState(null);
  const [meta, setMeta] = useState(null);
  const iframeRef = useRef(null);
  const { message } = AntApp.useApp();

  const load = async () => {
    try {
      setLoading(true);
      setError(null);
      let res;
      if (loadFn) {
        res = await loadFn();
      } else {
        if (!docType || !employeeId) return;
        res = await hrService.generateDocument(docType, employeeId, payslipId);
      }
      setHtml(res.html_content);
      setMeta(res.meta || null);
    } catch (e) {
      setError(e.message || 'Failed to generate document');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (open) load();
    else { setHtml(''); setError(null); setMeta(null); }
    // eslint-disable-next-line
  }, [open, docType, employeeId, payslipId]);

  const handlePrint = () => {
    const iframe = iframeRef.current;
    if (!iframe?.contentWindow) {
      message.warning('Document not ready yet');
      return;
    }
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch (e) {
      message.error('Print failed: ' + (e.message || 'unknown'));
    }
  };

  const handleDownloadHtml = () => {
    if (!html) return;
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const safeName = (employeeName || 'employee').replace(/[^a-z0-9]+/gi, '_').toLowerCase();
    a.href = url;
    a.download = `${safeName}_${docType}_${new Date().toISOString().slice(0, 10)}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = () => {
    handlePrint();
    message.info('Use "Save as PDF" in the print dialog to save a PDF');
  };

  const docTitle = title || DOC_TITLES[docType] || 'Document';

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent
        className="sm:max-w-[960px] w-[min(960px,95vw)] p-0 gap-0 max-h-[92vh]"
        showCloseButton={false}
      >
        {/* Header — gradient strip */}
        <DialogHeader className="px-6 py-4 bg-gradient-to-r from-indigo-600 via-indigo-500 to-blue-500 text-white">
          <div className="flex items-center gap-2">
            <FileText size={18} />
            <DialogTitle className="text-white">
              {docTitle}
              {employeeName && <span className="font-normal text-white/85"> · {employeeName}</span>}
            </DialogTitle>
          </div>
          {meta?.generated_at && (
            <div className="text-[11px] text-white/85 mt-1">
              Generated: {new Date(meta.generated_at || Date.now()).toLocaleString()}
            </div>
          )}
        </DialogHeader>

        {/* Iframe stage */}
        <div className="relative bg-slate-100 flex-1" style={{ height: '70vh' }}>
          {loading && (
            <div className="absolute inset-0 z-10 grid place-items-center bg-white/70 backdrop-blur-sm">
              <div className="flex flex-col items-center gap-3">
                <RefreshCw className="size-6 animate-spin text-indigo-600" />
                <div className="text-sm text-slate-600 font-medium">Generating document…</div>
              </div>
            </div>
          )}
          {error && !loading && (
            <div className="absolute inset-0 grid place-items-center p-6">
              <div className="max-w-sm text-center">
                <div className="mx-auto grid place-items-center size-12 rounded-full bg-rose-50 text-rose-600 ring-1 ring-rose-100 mb-3">
                  <AlertTriangle size={20} />
                </div>
                <div className="font-semibold text-slate-900">Couldn't generate document</div>
                <div className="text-sm text-slate-500 mt-1">{error}</div>
                <Button
                  className="mt-4 bg-gradient-to-r from-indigo-600 to-blue-500 text-white border-0"
                  onClick={load}
                >
                  Try again
                </Button>
              </div>
            </div>
          )}
          {!html && !error && !loading && <Skeleton className="h-full w-full" />}
          {html && !error && (
            <iframe
              ref={iframeRef}
              title={docTitle}
              srcDoc={html}
              sandbox="allow-same-origin allow-modals allow-popups allow-forms"
              className="w-full h-full border-0 bg-white"
            />
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-white">
          <TooltipProvider delayDuration={200}>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="ghost" size="icon" onClick={load} disabled={loading}>
                  <RefreshCw className={loading ? 'animate-spin' : ''} />
                </Button>
              </TooltipTrigger>
              <TooltipContent>Reload</TooltipContent>
            </Tooltip>
          </TooltipProvider>
          <Button variant="outline" onClick={handleDownloadHtml} disabled={!html || loading}>
            <FileType />
            Download HTML
          </Button>
          <Button variant="outline" onClick={handleDownloadPdf} disabled={!html || loading}>
            <Download />
            Save as PDF
          </Button>
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
          <Button
            onClick={handlePrint}
            disabled={!html || loading}
            className="bg-gradient-to-r from-indigo-600 to-blue-500 hover:from-indigo-700 hover:to-blue-600 text-white border-0 shadow-md shadow-indigo-500/25"
          >
            <Printer />
            Print
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
